### ISSUE TITLE
Add test to check for fix at tt_*()

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/fgeo.habitat#30]
See info from @srusso2 via [@](https://mail.google.com/mail/u/0/?zx=yxdmg1oh1mf4#search/label%3Aurgent+OR+label%3Atoday+OR+has%3Ared-star+OR+label%3Anotes+OR+is%3Aunread+NOT+label%3Awhere%2Fhome/lqrrRjrvPTCKDwLRKZpmznRKvSRnjnpXjGxzHpfFSzqpBFZVzHfDZDmTXHvjMTBtCcDBgtLQDDjcBvdvd).

**Comment by maurolepore** [comment]
@srusso2 ,

The notes you pointed me to say:
> The observed quantile for habitat 2 (Obs.Quantile.2) is 0.0094, so that's < 0.025, so it should get a "1" instead of "0" in the "Rep.Agg.Neut.2" column.

Did you really mean "1"? After the fix the result I get is instead "-1".

Here is the output:

```R
t(out)
                  KNEMLA
...
N.Hab.2        1710.0000
Gr.Hab.2         47.0000
Ls.Hab.2       4952.0000
Eq.Hab.2          1.0000
Rep.Agg.Neut.2   -1.0000
Obs.Quantile.2    0.0094
...
```

Here is the code that generated that output:

```r
# Issue 30, Sabrina Russo ----------------------------------------------------

# Original explanation of the error:
# The observed quantile for habitat 2 (Obs.Quantile.2) is 0.0094, so that's <
# 0.025, so it should get a "1" instead of "0" in the "Rep.Agg.Neut.2" column.

can_access_private_data <- dir.exists(test_path("private"))

if (can_access_private_data) {
  hab.index20 <- get(load(test_path("private/russo_30/hab.index20.Rdata")))
  allabund20 <- get(load(test_path("private/russo_30/allabund20.Rdata")))
  
  out <- fgeo.habitat:::torusonesp.all(
    species = "KNEMLA",
    hab.index20 = hab.index20,
    allabund20 = allabund20,
    plotdim = c(1000, 500),
    gridsize = 20
  )
  
  actual <- out[colnames(out) %in% "Rep.Agg.Neut.2"]
  test_that("torusonesp.all() with spp KNEMLA returns as expected (#30, Russo)", {
    # Only runs for those with access to private/ data
    skip_if(!can_access_private_data)
    
    expect_equal(actual, 1)
    expect_error(expect_equal(actual, 0), "not equal to 0")
  }) 
}
```

And here is the test that confirms that the expectation isn't met:

```R
Error: Test failed: 'torusonesp.all() with spp KNEMLA returns as expected (#30, Russo)'
* `actual` not equal to 1.
1/1 mismatches
[1] -1 - 1 == -2
```

**Comment by maurolepore** [comment]
Thanks @DanielZuleta and @srusso2! With your clarification below, it's clear now. I'll close this issue.

---

On Tue, Oct 23, 2018 at 12:51 AM Daniel Zuleta <dfzuleta@gmail.com> wrote:

> The only problem I found was a typing error (not in the code, but in the explanation for the previous bug). 

> The correct explanation should be: _The observed quantile for habitat 2 (Obs.Quantile.2) is 0.0094, so that's < 0.025, so it should get a "-1" instead of "0" in the "Rep.Agg.Neut.2" column_. 

> Values of the Obs.Quantile< 0.025 means that the species is repelled from that habitat, while values of the Obs.Quantile> 0.025 means that the species is aggregated on that habitat.


![image](https://user-images.githubusercontent.com/5856545/47356735-e330de00-d692-11e8-99b7-bb9ec54169b3.png)

**Comment by maurolepore** [comment]
Re-opened for @russo2 to review.

**Comment by DanielZuleta** [comment]
Mauro, sorry. Another typo mistake. Please modify the following green part
in that text:

Values of the Obs.Quantile< 0.025 means that the species is repelled from
that habitat, while values of the Obs.Quantile> *0.975* means that the
species is aggregated on that habitat.
